version: '3'
services: 
    master:
        build: 
            dockerfile: ./Master/Dockerfile
            context: .
        restart: always
        image: master_psql
        container_name: master
        hostname: master
        ports: 
            - 5432:5432
        volumes: 
            - ./master_volume:/var/lib/postgresql/data:z
        networks: 
            - psql_network
    
    slave:
        build:
            dockerfile: ./Slave/Dockerfile
            context: .
        restart: always
        image: slave_psql
        container_name: slave
        hostname: slave
        ports: 
            - 5433:5432
        volumes: 
            - ./slave_volume:/var/lib/postgresql/data:z
        networks: 
            - psql_network
        depends_on: 
            - master

networks: 
    psql_network:
        driver: bridge
